export const VOWELS = ['Аа', 'Ее', 'Ëё', 'Ии', 'Оо', 'Уу', 'Ыы', 'Ээ', 'Юю', 'Яя'];

export const DICTIONARY_FIRST_VOWELS = [
    {eng: 'automobile', ru: 'автомобиль'},
    {eng: 'watermelon', ru: 'арбуз'},
    {eng: 'stork', ru: 'аист'},
    {eng: 'pineapple', ru: 'ананас'},
    {eng: 'amulet', ru: 'амулет'},
    {eng: 'aquarium', ru: 'аквариум'},
    {eng: 'shark', ru: 'акула'},
    {eng: 'avocado', ru: 'авокадо'},
    {eng: 'angel', ru: 'ангел'},
    {eng: 'crossbow', ru: 'арбалет'},
    {eng: 'airplane', ru: 'аэроплан'},
    {eng: 'orange', ru: 'апельсин'},
    {eng: 'aloe', ru: 'алоэ'},
    {eng: 'ak47', ru: 'автомат'},
    {eng: 'bus', ru: 'автобус'},
    {eng: 'iceberg', ru: 'айсберг'},
    {eng: 'antelope', ru: 'антилопа'},
    {eng: 'accordion', ru: 'аккордеон'},
    {eng: 'raccoon', ru: 'енот'},
    {eng: 'unicorn', ru: 'единорог'},
    {eng: 'blackberry', ru: 'ежевика'},
    {eng: 'hedgehog', ru: 'ёжик'},
    {eng: 'Christmas tree', ru: 'ёлка'},
    {eng: 'brush', ru: 'ёршик'},
    {eng: 'needle', ru: 'игла'},
    {eng: 'Indian', ru: 'индеец'},
    {eng: 'turkey', ru: 'индейка'},
    {eng: 'fig', ru: 'инжир'},
    {eng: 'ginger', ru: 'имбирь'},
    {eng: 'interview', ru: 'интервью'},
    {eng: 'emerald', ru: 'изумруд'},
    {eng: 'iguana', ru: 'игуана'},
    {eng: 'oriole', ru: 'иволга'},
    {eng: 'willow', ru: 'ива'},
    {eng: 'raisin', ru: 'изюм'},
    {eng: 'eagle', ru: 'орел'},
    {eng: 'donkey', ru: 'ослик'},
    {eng: 'lamb', ru: 'овечка'},
    {eng: 'light', ru: 'огонек'},
    {eng: 'window', ru: 'окно'},
    {eng: 'cucumber', ru: 'огурец'},
    {eng: 'dandelion', ru: 'одуванчик'},
    {eng: 'deer', ru: 'олень'},
    {eng: 'nut', ru: 'орех'},
    {eng: 'orange', ru: 'оранжевый'},
    {eng: 'autumn', ru: 'осень'},
    {eng: 'dinner', ru: 'обед'},
    {eng: 'monkey', ru: 'обезьяна'},
    {eng: 'lake', ru: 'озеро'},
    {eng: 'eagle', ru: 'орел'},
    {eng: 'ocean', ru: 'океан'},
    {eng: 'snail', ru: 'улитка'},
    {eng: 'duck', ru: 'утка'},
    {eng: 'iron', ru: 'утюг'},
    {eng: 'smile', ru: 'улыбка'},
    {eng: 'knot', ru: 'узел'},
    {eng: 'textbook', ru: 'учебник'},
    {eng: 'ukulele', ru: 'укулеле'},
    {eng: 'duckling', ru: 'утёнок'},
    {eng: 'hive', ru: 'улей'},
    {eng: 'coal', ru: 'уголь'},
    {eng: 'platypus', ru: 'утконос'},
    {eng: 'trash can', ru: 'урна'},
    {eng: 'ear', ru: 'ухо'},
    {eng: 'dill', ru: 'укроп'},
    {eng: 'syringe injection', ru: 'укол'},
    {eng: 'already', ru: 'уж'},
    {eng: 'acne', ru: 'угорь'},
    {eng: 'boa', ru: 'удав'},
    {eng: 'electron', ru: 'электрон'},
    {eng: 'electricity', ru: 'электричество'},
    {eng: 'screen', ru: 'экран'},
    {eng: 'popsicle ice cream', ru: 'эскимо'},
    {eng: 'encyclopedia', ru: 'энциклопедия'},
    {eng: 'exoskeleton', ru: 'экзоскелет'},
    {eng: 'elf', ru: 'эльф'},
    {eng: 'escalator', ru: 'эскалатор'},
    {eng: 'equilibrist', ru: 'эквилибрист'},
    {eng: 'relay race', ru: 'эстафета'},
    {eng: 'sketch', ru: 'эскиз'},
    {eng: 'power station', ru: 'электростанция'},
    {eng: 'yula', ru: 'юла'},
    {eng: 'yurt', ru: 'юрта'},
    {eng: 'Jurassic period', ru: 'юрский период'},
    {eng: 'lawyer in court', ru: 'юрист'},
    {eng: 'jeweler', ru: 'ювелир'},
    {eng: 'skirt', ru: 'юбка'},
    {eng: 'South Pole', ru: 'южный полюс'},
    {eng: 'humor', ru: 'юмор'},
    {eng: 'bird yurok', ru: 'юрок'},
    {eng: 'apple', ru: 'яблоко'},
    {eng: 'berry', ru: 'ягода'},
    {eng: 'hawk', ru: 'ястреб'},
    {eng: 'anchor', ru: 'якорь'},
    {eng: 'lizard', ru: 'ящерица'},
    {eng: 'fried eggs', ru: 'яичница'},
    {eng: 'fair', ru: 'ярмарка'},
    {eng: 'poison', ru: 'яд'},
    {eng: 'language', ru: 'язык'},
    {eng: 'Japan', ru: 'япония'},
    {eng: 'yacht', ru: 'яхта'},
    {eng: 'egg', ru: 'яйцо'},
    {eng: 'label', ru: 'ярлык'},
    {eng: 'pit', ru: 'яма'},
    {eng: 'jaguar', ru: 'ягуар'},
    {eng: 'ash', ru: 'ясень'},
    {eng: 'amber', ru: 'янтарь'},
    {eng: 'lamb', ru: 'ягнёнок'},
];
